#! /usr/bin/env node

const { Client } = require("pg");
process.loadEnvFile();

const SQL = `
DROP TABLE IF EXISTS Games CASCADE;
DROP TABLE IF EXISTS Developers CASCADE;
DROP TABLE IF EXISTS Genres CASCADE;

CREATE TABLE Genres (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(100) NOT NULL,
    info VARCHAR(200) NOT NULL
);

CREATE TABLE Developers (
    developer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_name VARCHAR(100) NOT NULL,
    location VARCHAR(50) NOT NULL,
    other_games VARCHAR(300) NOT NULL
);

CREATE TABLE Games (
    game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age_rating VARCHAR(50) NOT NULL,
    score INT NOT NULL,
    image_url TEXT,
    genre_id INT,
    developer_id INT,
    
    FOREIGN KEY (genre_id) REFERENCES Genres(genre_id),
    FOREIGN KEY (developer_id) REFERENCES Developers(developer_id) 
);

INSERT INTO Genres (genre_id, genre_name, info) VALUES
(1, 'Action RPG', 'Role-playing games with real-time combat and character progression.'),
(2, 'Soulslike', 'Challenging action games focused on stamina, timing, and environmental storytelling.'),
(3, 'Action-Adventure', 'Combines exploration, narrative-driven quests, and fluid real-time combat.'),
(4, 'Roguelike', 'Features procedurally generated levels, permadeath, and run-based gameplay.'),
(5, 'Turn-Based RPG', 'Role-playing games where combat actions are executed in alternating turns.'),
(6, 'First-Person Shooter', 'Shooting games centered on gunplay through the character eyes.'),
(7, 'Interactive Drama', 'Narrative-driven cinematic experiences shaped heavily by player choices.'),
(8, 'Metroidvania', 'Non-linear interconnected platforming with ability-gated progression.'),
(9, 'Survival Horror', 'Atmospheric games prioritizing resource conservation, vulnerability, and tension.'),
(10, 'Open World Adventure', 'Expansive non-linear sandbox environments with emergent exploration.'),
(11, 'Stealth', 'Emphasizes evasion, concealment, and tactical planning over direct confrontation.'),
(12, 'Platformer', 'Focuses on navigating terrain through jumping, precision climbing, and timing.'),
(13, 'Immersive Sim', 'Provides deep systemic mechanics and multiple emergent solutions to problems.'),
(14, 'Hack and Slash', 'Fast-paced, combo-heavy melee combat against large groups of enemies.'),
(15, 'Tactical RPG', 'Grid-based or positioning-heavy strategy combined with role-playing progression.'),
(16, 'Psychological Horror', 'Focuses on mental and emotional dread, unreliable reality, and narrative tension.');

INSERT INTO Developers (developer_id, developer_name, location, other_games) VALUES
(101, 'CD Projekt Red', 'Warsaw, Poland', 'The Witcher 2: Assassins of Kings, Cyberpunk 2077'),
(102, 'FromSoftware', 'Tokyo, Japan', 'Dark Souls, Bloodborne, Armored Core VI'),
(103, 'Insomniac Games', 'Burbank, USA', 'Ratchet & Clank: Rift Apart, Resistance, Sunset Overdrive'),
(104, 'Santa Monica Studio', 'Los Angeles, USA', 'God of War (2005), God of War II, God of War III'),
(105, 'Remedy Entertainment', 'Espoo, Finland', 'Alan Wake, Max Payne, Quantum Break'),
(106, 'Housemarque', 'Helsinki, Finland', 'Resogun, Nex Machina, Matterfall'),
(107, 'Sucker Punch Productions', 'Bellevue, USA', 'Infamous, Sly Cooper, Infamous Second Son'),
(108, 'Quantic Dream', 'Paris, France', 'Heavy Rain, Beyond: Two Souls, Fahrenheit'),
(109, 'Warhorse Studios', 'Prague, Czech Republic', 'Kingdom Come: Deliverance'),
(110, 'Larian Studios', 'Ghent, Belgium', 'Divinity: Original Sin, Divinity: Original Sin II'),
(111, 'Capcom', 'Osaka, Japan', 'Monster Hunter: World, Devil May Cry 5, Dragon''s Dogma 2'),
(112, 'BioWare', 'Edmonton, Canada', 'Mass Effect 2, Dragon Age: Origins, Baldur''s Gate II'),
(113, 'Arkane Studios', 'Lyon, France', 'Dishonored 2, Prey, Deathloop'),
(114, 'Team Cherry', 'Adelaide, Australia', 'Hollow Knight: Silksong'),
(115, 'Supergiant Games', 'San Francisco, USA', 'Bastion, Transistor, Pyre'),
(116, 'Obsidian Entertainment', 'Irvine, USA', 'Fallout: New Vegas, Pillars of Eternity, The Outer Worlds');

INSERT INTO Games (game_id, name, age_rating, score, image_url, genre_id, developer_id) VALUES
(1, 'The Witcher 3: Wild Hunt', 'Mature 17+', 93, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg', 1, 101),
(2, 'Elden Ring', 'Mature 17+', 96, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg', 2, 102),
(3, 'Marvel''s Spider-Man', 'Teen', 87, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r77.jpg', 3, 103),
(4, 'God of War Ragnarök', 'Mature 17+', 94, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg', 3, 104),
(5, 'Control', 'Mature 17+', 82, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1vce.jpg', 3, 105),
(6, 'Returnal', 'Mature 17+', 86, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2k7m.jpg', 4, 106),
(7, 'Ghost of Tsushima', 'Mature 17+', 83, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2crj.jpg', 10, 107),
(8, 'Detroit: Become Human', 'Mature 17+', 78, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rbi.jpg', 7, 108),
(9, 'Kingdom Come: Deliverance II', 'Mature 17+', 89, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co820h.jpg', 1, 109),
(10, 'Baldur''s Gate 3', 'Mature 17+', 96, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co670h.jpg', 5, 110),
(11, 'Bloodborne', 'Mature 17+', 92, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rba.jpg', 2, 102),
(12, 'Cyberpunk 2077', 'Mature 17+', 86, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2mjt.jpg', 1, 101),
(13, 'Alan Wake 2', 'Mature 17+', 89, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6k1r.jpg', 9, 105),
(14, 'Resident Evil 4', 'Mature 17+', 93, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5u.jpg', 9, 111),
(15, 'Devil May Cry 5', 'Mature 17+', 89, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1t8l.jpg', 14, 111),
(16, 'Monster Hunter: World', 'Teen', 90, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rag.jpg', 1, 111),
(17, 'Star Wars: Knights of the Old Republic', 'Teen', 93, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1trn.jpg', 1, 112),
(18, 'Mass Effect 2', 'Mature 17+', 96, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x77.jpg', 1, 112),
(19, 'Dishonored', 'Mature 17+', 91, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1m38.jpg', 13, 113),
(20, 'Prey', 'Mature 17+', 82, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ra9.jpg', 13, 113),
(21, 'Hollow Knight', 'Everyone 10+', 90, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9387.jpg', 8, 114),
(22, 'Hades', 'Teen', 93, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.jpg', 4, 115),
(23, 'Hades II', 'Teen', 92, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5p14.jpg', 4, 115),
(24, 'Fallout: New Vegas', 'Mature 17+', 84, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rac.jpg', 1, 116),
(25, 'Pillars of Eternity', 'Mature 17+', 89, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rb5.jpg', 5, 116),
(26, 'Armored Core VI: Fires of Rubicon', 'Teen', 86, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co644w.jpg', 3, 102),
(27, 'Ratchet & Clank: Rift Apart', 'Everyone 10+', 88, 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2m37.jpg', 12, 103);

SELECT setval(pg_get_serial_sequence('games', 'game_id'), coalesce(max(game_id), 0) + 1, false) FROM games;
SELECT setval(pg_get_serial_sequence('genres', 'genre_id'), coalesce(max(genre_id), 0) + 1, false) FROM genres;
SELECT setval(pg_get_serial_sequence('developers', 'developer_id'), coalesce(max(developer_id), 0) + 1, false) FROM developers;
`;

async function main() {
  const connectionString = process.argv[2] || process.env.connectionstring;

  if (!connectionString) {
    console.error("No connection string found in .env or arguments.");
    process.exit(1);
  }

  console.log("Seeding database...");

  const isRemote =
    connectionString.includes("neon.tech") ||
    connectionString.includes("sslmode=require");

  const client = new Client({
    connectionString,
    ssl: isRemote ? { rejectUnauthorized: false } : false,
  });

  try {
    await client.connect();
    await client.query(SQL);
    console.log("Database seeded successfully!");
  } catch (err) {
    console.error("Error executing seed script:", err);
  } finally {
    await client.end();
  }
}

main();
